# Generated by Django 4.1.7 on 2023-04-07 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubscriptionOnAuthor",
            new_name="Subscription",
        ),
    ]
