# Generated by Django 4.1.7 on 2023-04-04 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_subscribauthor_unique appversion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_user_admin",
        ),
    ]
