# Generated by Django 4.1.7 on 2023-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "verbose_name": "Избранный рецет",
                "verbose_name_plural": "Избранные рецеты",
            },
        ),
        migrations.AlterField(
            model_name="baseingredient",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Название продукта"),
        ),
    ]
