# Generated by Django 4.1.7 on 2023-04-08 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_favorite_subscribed_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_ingredient",
                to="recipes.baseingredient",
                verbose_name="Название продукта",
            ),
        ),
    ]
