# Generated by Django 4.1.7 on 2023-04-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_ingredient_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient",
                to="recipes.baseingredient",
                verbose_name="Название продукта",
            ),
        ),
    ]
