# Generated by Django 4.1.7 on 2023-04-08 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_alter_ingredient_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="amount",
            field=models.IntegerField(
                blank=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество продукта",
            ),
        ),
    ]
