# Generated by Django 4.1.7 on 2023-04-09 08:05

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0008_alter_ingredient_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseingredient",
            options={
                "ordering": ("name",),
                "verbose_name": "Product Name",
                "verbose_name_plural": "Products Name",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "verbose_name": "Favorite Recipe",
                "verbose_name_plural": "Favorite Recipes",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ("ingredient",),
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppinglist",
            options={
                "verbose_name": "Shopping List",
                "verbose_name_plural": "Shopping Lists",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name",),
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterField(
            model_name="baseingredient",
            name="measurement_unit",
            field=models.CharField(max_length=32, verbose_name="Measurement Unit"),
        ),
        migrations.AlterField(
            model_name="baseingredient",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="subscribed_recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_subscribed_recipe",
                to="recipes.recipe",
                verbose_name="Recipe",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="amount",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantity of Product",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient",
                to="recipes.baseingredient",
                verbose_name="Product Name",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="to_recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_to_recipe",
                to="recipes.recipe",
                verbose_name="Recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_recipe",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cooking Time in Minutes",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="recipes/image/",
                verbose_name="Recipe image",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                to="recipes.baseingredient", verbose_name="Ingredients"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Recipe Name"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Publication Date"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="tags", to="recipes.tag", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.TextField(max_length=256, verbose_name="Recipe Discription"),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="subscribed_recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoppinglist_subscribed_recipe",
                to="recipes.recipe",
                verbose_name="Recipe",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoppinglist_subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=18,
                samples=None,
                unique=True,
                verbose_name="Tag Color",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=32, unique=True, verbose_name="Tag Name"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Tag Slug"),
        ),
    ]
