# Generated by Django 4.1.7 on 2023-04-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0009_alter_baseingredient_options_alter_favorite_options_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["subscriber", "subscribed_recipe"],
                name="recipes_fav_subscri_6eb5ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(
                fields=["ingredient"], name="recipes_ing_ingredi_602db0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoppinglist",
            index=models.Index(
                fields=["subscriber", "subscribed_recipe"],
                name="recipes_sho_subscri_ff6def_idx",
            ),
        ),
    ]
