# Generated by Django 4.1.7 on 2023-04-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="recipes/image/",
                verbose_name="Изображение рецепта",
            ),
        ),
    ]
